"""Data models for Max Bot API."""

from maxbot.schemes.models import (
    # Attachments
    Attachment,
    AttachmentPayload,
    AttachmentRequest,
    AudioAttachment,
    AudioAttachmentPayload,
    AudioAttachmentRequest,
    ContactAttachment,
    ContactAttachmentPayload,
    ContactAttachmentRequest,
    FileAttachment,
    FileAttachmentPayload,
    FileAttachmentRequest,
    InlineKeyboardAttachment,
    InlineKeyboardAttachmentPayload,
    LocationAttachment,
    LocationAttachmentPayload,
    LocationAttachmentRequest,
    MediaAttachmentPayload,
    PhotoAttachment,
    PhotoAttachmentPayload,
    PhotoAttachmentRequest,
    PhotoToken,
    ShareAttachment,
    ShareAttachmentPayload,
    StickerAttachment,
    StickerAttachmentPayload,
    VideoAttachment,
    VideoAttachmentPayload,
    VideoAttachmentRequest,
    # Bot
    BotCommand,
    BotInfo,
    BotPatch,
    # Buttons
    Button,
    CallbackButton,
    ChatButton,
    LinkButton,
    OpenAppButton,
    RequestContactButton,
    RequestGeoLocationButton,
    # Chat
    Chat,
    ChatAdminsResult,
    ChatList,
    ChatMember,
    ChatMembersResult,
    ChatPatch,
    ChatStatus,
    ChatType,
    # Keyboard
    Keyboard,
    # Message
    LinkedMessage,
    Message,
    MessageBody,
    MessageCallbackResult,
    MessageList,
    MessageStat,
    NewMessageBody,
    NewMessageLink,
    SendMessageResult,
    # Recipient
    Recipient,
    # Subscription
    GetSubscriptionsResult,
    SimpleQueryResult,
    Subscription,
    SubscriptionRequestBody,
    # Updates
    BotAddedToChatUpdate,
    BotRemovedFromChatUpdate,
    BotStartedUpdate,
    Callback,
    ChatTitleChangedUpdate,
    MessageCallbackUpdate,
    MessageChatCreatedUpdate,
    MessageCreatedUpdate,
    MessageEditedUpdate,
    MessageConstructedUpdate,
    MessageConstructionRequest,
    MessageRemovedUpdate,
    Update,
    UpdateList,
    UserAddedToChatUpdate,
    UserRemovedFromChatUpdate,
    # Upload
    UploadEndpoint,
    UploadType,
    UploadedInfo,
    # User
    User,
    UserIdsList,
    UserWithPhoto,
    # Action
    ActionRequestBody,
    SenderAction,
)

__all__ = [
    # Attachments
    "Attachment",
    "AttachmentPayload",
    "AttachmentRequest",
    "AudioAttachment",
    "AudioAttachmentPayload",
    "AudioAttachmentRequest",
    "ContactAttachment",
    "ContactAttachmentPayload",
    "ContactAttachmentRequest",
    "FileAttachment",
    "FileAttachmentPayload",
    "FileAttachmentRequest",
    "InlineKeyboardAttachment",
    "InlineKeyboardAttachmentPayload",
    "LocationAttachment",
    "LocationAttachmentPayload",
    "LocationAttachmentRequest",
    "MediaAttachmentPayload",
    "PhotoAttachment",
    "PhotoAttachmentPayload",
    "PhotoAttachmentRequest",
    "PhotoToken",
    "ShareAttachment",
    "ShareAttachmentPayload",
    "StickerAttachment",
    "StickerAttachmentPayload",
    "VideoAttachment",
    "VideoAttachmentPayload",
    "VideoAttachmentRequest",
    # Bot
    "BotCommand",
    "BotInfo",
    "BotPatch",
    # Buttons
    "Button",
    "CallbackButton",
    "ChatButton",
    "LinkButton",
    "OpenAppButton",
    "RequestContactButton",
    "RequestGeoLocationButton",
    # Chat
    "Chat",
    "ChatAdminsResult",
    "ChatList",
    "ChatMember",
    "ChatMembersResult",
    "ChatPatch",
    "ChatStatus",
    "ChatType",
    # Keyboard
    "Keyboard",
    # Message
    "LinkedMessage",
    "Message",
    "MessageBody",
    "MessageCallbackResult",
    "MessageList",
    "MessageStat",
    "NewMessageBody",
    "NewMessageLink",
    "SendMessageResult",
    # Recipient
    "Recipient",
    # Subscription
    "GetSubscriptionsResult",
    "SimpleQueryResult",
    "Subscription",
    "SubscriptionRequestBody",
    # Updates
    "BotAddedToChatUpdate",
    "BotRemovedFromChatUpdate",
    "BotStartedUpdate",
    "Callback",
    "ChatTitleChangedUpdate",
    "MessageCallbackUpdate",
    "MessageChatCreatedUpdate",
    "MessageCreatedUpdate",
    "MessageEditedUpdate",
    "MessageConstructedUpdate",
    "MessageConstructionRequest",
    "MessageRemovedUpdate",
    "Update",
    "UpdateList",
    "UserAddedToChatUpdate",
    "UserRemovedFromChatUpdate",
    # Upload
    "UploadEndpoint",
    "UploadType",
    "UploadedInfo",
    # User
    "User",
    "UserIdsList",
    "UserWithPhoto",
    # Action
    "ActionRequestBody",
    "SenderAction",
]
